node {
   def mvnHome
   stage('Preparation') { // for display purposes
      // Get some code from a GitHub repository
      git 'https://github.com/mayureshkrishna/simple/'
      // Get the Maven tool.
      // ** NOTE: This 'M3' Maven tool must be configured
      // **       in the global configuration.           
      mvnHome = tool 'Maven'
   }
   stage('Build') {
      // Run the maven build
      if (isUnix()) {
         sh "'mvn' -Dmaven.test.failure.ignore clean package"
      } else {
         bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean package/)
      }
   }
   stage('Deploy') {
       //Deploy to Cloud Foundry
       pushToCloudFoundry cloudSpace: 'alpha', credentialsId: 'CF-PEZ69', organization: 'DemoOrg', selfSigned: 'true', target: 'api.run.haas-69.pez.pivotal.io'

   }
   stage('Results') {
      junit '**/target/surefire-reports/TEST-*.xml'
   }
}
